### PR TITLE
Crc navids masterpiece

### PR DESCRIPTION
**Pull request by Imperatoras**
Git has stopped acting up! This is the CRC code merged with master, and now it can auto-merge.

### CODE REVIEW

**Comment by justinkim** [comment]
It looks like there are still some merge conflicts to be resolved. Double-check the changes introduced by your commits.

**Review by yuna9 — CHANGES_REQUESTED** [review]
It looks like there are still some merge conflicts to be resolved. Double-check the changes introduced by your commits.

**Comment by Imperatoras** [comment]
Apologies, it turns out we were in the wrong directory, so I couldn't see the conflicts. They've been corrected and pushed to this branch. Could you look over it and approve the request? Thanks!

**Comment by Imperatoras** [comment]
Can someone please go over this? I pushed new code to the branch. Thank you.

**Review by PrathamRawat — CHANGES_REQUESTED** [review]
It seems like you're pushing changes that aren't meant to be pushed, like .classpath and eclipse preferences and settings. Please remove those. Otherwise, everything seems to be good!

**Pull request closed without merging**
